"""empty message

Revision ID: 39446dc51b8f
Revises: b1952207f906
Create Date: 2019-03-02 20:15:14.421221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39446dc51b8f'
down_revision = 'b1952207f906'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phoneNumber', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('phoneNumber')
    )
    op.create_unique_constraint(None, 'book', ['title'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'book', type_='unique')
    op.drop_table('customers')
    # ### end Alembic commands ###
